---
- name: Installer Mariadb server
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Activer et demarrer Mariadb
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Installer dépendance Python pour Mariadb
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Definir mot de passe root Mariadb
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: yes

- name: Créer bdd app
  community.mysql.mysql_db:
    name: "{{ app_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: yes

- name: Créer utilisateur app et donner droits
  community.mysql.mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    host: "%"
    priv: "{{ app_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: yes
